package overlay

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// pyprojectTmpl is the PEP 621 pyproject.toml template for generated Python packages.
var pyprojectTmpl = template.Must(template.New("pyproject").Parse(`[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ .DistName }}"
version = "0.0.0.dev0"
requires-python = ">=3.9"
dependencies = [
    "grpcio>=1.60",
    "protobuf>=4.25",
]

[tool.setuptools.packages.find]
include = ["{{ .Namespace }}*"]
`))

// ScaffoldPythonPackage generates a Python package structure inside an overlay directory.
//
// It creates:
//   - pyproject.toml with PEP 621 metadata
//   - __init__.py hierarchy for namespace packages (using pkgutil.extend_path)
//
// Parameters:
//   - overlayPath: absolute path to the overlay directory (e.g. internal/gen/python/proto/payments/ledger/v1/)
//   - distName: PEP 625 distribution name (e.g. "acme-payments-ledger-v1")
//   - importRoot: dotted import path (e.g. "acme_apis.payments.ledger.v1")
func ScaffoldPythonPackage(overlayPath, distName, importRoot string) error {
	// Write pyproject.toml
	namespace := strings.SplitN(importRoot, ".", 2)[0]
	pyprojectPath := filepath.Join(overlayPath, "pyproject.toml")
	f, err := os.Create(pyprojectPath)
	if err != nil {
		return fmt.Errorf("creating pyproject.toml: %w", err)
	}
	defer f.Close()

	if err := pyprojectTmpl.Execute(f, struct {
		DistName  string
		Namespace string
	}{
		DistName:  distName,
		Namespace: namespace,
	}); err != nil {
		return fmt.Errorf("rendering pyproject.toml: %w", err)
	}

	// Build __init__.py hierarchy
	parts := strings.Split(importRoot, ".")
	if len(parts) == 0 {
		return fmt.Errorf("empty import root")
	}

	currentDir := overlayPath
	for i, part := range parts {
		currentDir = filepath.Join(currentDir, part)
		if err := os.MkdirAll(currentDir, 0755); err != nil {
			return fmt.Errorf("creating package directory %s: %w", currentDir, err)
		}

		initPath := filepath.Join(currentDir, "__init__.py")
		isLeaf := i == len(parts)-1
		isNamespace := i == 0

		var content string
		if isLeaf {
			content = "# Generated by apx — leaf package for generated code.\n"
		} else if isNamespace {
			// Top-level namespace package uses pkgutil.extend_path so
			// multiple distributions can contribute to the same namespace.
			content = fmt.Sprintf(
				"# Namespace package — do not add code here.\n" +
					"from pkgutil import extend_path\n" +
					"__path__ = extend_path(__path__, __name__)  # type: ignore[has-type]\n",
			)
		} else {
			content = "# Generated by apx — intermediate namespace package.\n"
		}

		if err := os.WriteFile(initPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", initPath, err)
		}
	}

	return nil
}
